services:
  worker:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_ROLE_ARN: ${AWS_ROLE_ARN}
volumes:
  minio_storage: {}
  mongodb_data: {}
