services:
  yarn:
    build:
      context: ${APP_DIR}
      target: dev
    command: yarn
    volumes:
      - ${APP_DIR}/:/opt/epp-client/
      - node_modules:/opt/epp-client/node_modules
  app:
    image: app-local
    build:
      context: ${APP_DIR}
      dockerfile: Dockerfile
      target: dev
    depends_on:
      yarn:
        condition: service_completed_successfully
    ports:
      - 3001:3000
    volumes:
      - ${APP_DIR}/:/opt/epp-client/
      - node_modules:/opt/epp-client/node_modules

volumes:
  node_modules:
