services:
  # mount mock-data/meca, copy .meca and .zip to minio biorxiv s3
  loadbucket:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      createbucket:
        condition: service_completed_successfully
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio miniotest;
      /usr/bin/mc cp --recursive /mock-meca/*.meca /mock-meca/*.zip myminio/biorxiv/;
      exit 0;
      "
    volumes:
      - ./mock-data/meca:/mock-meca

  # start worker after loaded bucket
  worker:
    depends_on:
      loadbucket:
        condition: service_completed_successfully

  # mock datahub docmaps api
  mock-datahub:
    image: nginx:latest
    ports:
      - 3002:80
    volumes:
      - ./.docker/nginx-datahub-mock.conf:/etc/nginx/conf.d/default.conf
      - ./mock-data/docmaps:/www/test-data/
