services:
  # mount mock-data/meca, copy .meca and .zip to minio biorxiv s3
  loadbucket:
    image: minio/mc:RELEASE.2022-12-24T15-21-38Z
    depends_on:
      createbucket:
        condition: service_completed_successfully
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio miniotest;
      /usr/bin/mc cp --recursive /mock-meca/*.meca /mock-meca/*.zip myminio/biorxiv/;
      exit 0;
      "
    volumes:
      - ./mock-data/meca:/mock-meca

  # set BIORXIV_URI
  worker:
    environment:
      BIORXIV_URI: http://mock-biorxiv

  # mock datahub docmaps api
  mock-datahub:
    image: nginx:latest
    ports:
      - 3002:80
    volumes:
      - ./.docker/nginx-datahub-mock.conf:/etc/nginx/conf.d/default.conf
      - ./mock-data/docmaps:/www/test-data/

  # mock biorxiv api
  mock-biorxiv:
    image: nginx:latest
    ports:
      - 3003:80
    volumes:
      - ./.docker/nginx-biorxiv-mock.conf:/etc/nginx/conf.d/default.conf
      - ./mock-data/meca:/www/test-data/
